some tests for fileIO
Jhsmit/PyHDX pull request #183
Opened 2021-03-09 14:20 UTC by sajetan

PR to know if this works the way I expected.

2021-03-10 09:24 UTC, Jhsmit requested changes

2021-03-10 09:24 UTC, Jhsmit commented on tests/test_fileIO.py
> +from pyhdx.fileIO import txt_to_protein, txt_to_np, read_dynamx, fmt_export, _get_f_width
`_get_f_width` is imported but not used

2021-03-10 09:24 UTC, Jhsmit commented on tests/test_fileIO.py
> +        txt_to_protein(path)
This is good but you should include an `assert` when you add a function for testing. Here the `txt_to_protein` returns an object, so you could write an assert to check if this is the correct object, and then another which checks if the data in the object is as expected

2021-03-10 09:24 UTC, Jhsmit commented on tests/test_fileIO.py
> +            txt_to_np(StringIO('f'))
Same for this function

`array = txt_to_np(...)`
then 
assert array[some selection] == known_value

2021-03-10 20:45 UTC, sajetan commented
reviewed and added some more changes

2021-03-12 09:23 UTC, Jhsmit approved these changes

2021-03-12 09:23 UTC, merged